security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\AppAuthenticator
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
            logout:
                path: logout
                target: home

    access_control:
        - { path: ^/admin, roles: [ ROLE_ADMIN, ROLE_CASHIER ] }
        - { path: ^/dashboard, roles: ROLE_USER }
